[toolchain]
anchor_version = "1.0.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
halo = "HUd9rbV6jTCD6HUufKRdFNx4jc7qhxAusejXDkZZ1KF7"

[programs.localnet]
halo = "HUd9rbV6jTCD6HUufKRdFNx4jc7qhxAusejXDkZZ1KF7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
